---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io1-50
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: io1
  iopsPerGB: "50"
  encrypted: "true"
