---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: io2-32000
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: io2
  iops: "32000"
  encrypted: "true"
