---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: mariadb
      name: mariadb
    spec:
      storageClassName: io1-32000
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: mariadb
      name: mariadb
    stringData:
      database-name: do120db
      database-password: redhat
      database-root-password: redhat
      database-user: operator1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: mariadb
      name: mariadb
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mariadb
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: mariadb
        spec:
          volumes:
            - name: mariadb-data
              persistentVolumeClaim:
                claimName: mariadb
          containers:
            - name: mariadb
              image: registry.redhat.io/rhel9/mariadb-105
              volumeMounts:
                - mountPath: /var/lib/mysql/data
                  name: mariadb-data
              ports:
                - containerPort: 3306
              env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mariadb
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: mariadb
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-root-password
                      name: mariadb
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: mariadb
              livenessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
                initialDelaySeconds: 30
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
                initialDelaySeconds: 5
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: mariadb
      name: mariadb
    spec:
      ports:
        - name: mariadb
          port: 3306
      selector:
        name: mariadb
