---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: hello-world-nginx
      name: hello-world-nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hello-world-nginx
      template:
        metadata:
          labels:
            app: hello-world-nginx
        spec:
          containers:
            - name: hello-world-nginx
              image: quay.io/redhattraining/hello-world-nginx:v1.0
              ports:
                - containerPort: 8080
              readinessProbe:
                initialDelaySeconds: 10
                httpGet:
                  path: /index.html
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 30
                httpGet:
                  path: /index.html
                  port: 8080
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hello-world-nginx
      name: hello-world-nginx
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: hello-world-nginx
