kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: low-cost-sc
provisioner: disk.csi.azure.com
parameters:
  kind: managed
  storageaccounttype: StandardSSD_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
